# Generated by Django 5.1.2 on 2024-10-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_complaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
